In [2]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, accuracy_score
import time

In [4]:
#1. 데이터
datasets = load_iris()
# print(datasets.DESCR)
# print(datasets.feature_names)

In [5]:
x= datasets.data
y= datasets.target
print(x)
print(y)
print(x.shape, y.shape)  # (150, 4) (150,)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
# One Hot Encoding
from keras.utils import to_categorical
y = to_categorical(y)
print(y)
print(y.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [7]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, train_size=0.8, shuffle=True, random_state=72
)
print(x_train.shape, y_train.shape) # (120, 4) (120, 3)

(120, 4) (120, 3)


In [8]:
#2. 모델구성
model = Sequential()
model.add(Dense(100, input_dim=4))
model.add(Dense(50))
model.add(Dense(10))
model.add(Dense(3, activation='softmax'))

In [9]:
#3. 컴파일, 훈련
model.compile(loss='categorical_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [12]:
#EarlyStopping
earlyStopping = EarlyStopping(monitor='val_loss', patience=50, mode='min',
                             verbose=1, restore_best_weights=True)

start_time = time.time()
hist = model.fit(x_train, y_train, epochs=1000, batch_size=10,
                validation_split=0.2, 
                callbacks=[earlyStopping],
                verbose=1)
end_time = time.time() - start_time
print('걸린 시간 : ', end_time) # Epoch 00087: early stopping
                                # 걸린 시간 :  8.603594064712524

Epoch 1/1000
10/10 [==============================] - 0s 8ms/step - loss: 0.0943 - accuracy: 0.9688 - val_loss: 0.0620 - val_accuracy: 0.9583
Epoch 2/1000
10/10 [==============================] - 0s 8ms/step - loss: 0.0869 - accuracy: 0.9792 - val_loss: 0.0301 - val_accuracy: 1.0000
Epoch 3/1000
10/10 [==============================] - 0s 8ms/step - loss: 0.1050 - accuracy: 0.9375 - val_loss: 0.1321 - val_accuracy: 0.9583
Epoch 4/1000
10/10 [==============================] - 0s 9ms/step - loss: 0.1766 - accuracy: 0.9479 - val_loss: 0.0200 - val_accuracy: 1.0000
Epoch 5/1000
10/10 [==============================] - 0s 7ms/step - loss: 0.1182 - accuracy: 0.9479 - val_loss: 0.1191 - val_accuracy: 0.9583
Epoch 6/1000
10/10 [==============================] - 0s 7ms/step - loss: 0.1443 - accuracy: 0.9271 - val_loss: 0.0521 - val_accuracy: 0.9583
Epoch 7/1000
10/10 [==============================] - 0s 7ms/step - loss: 0.1099 - accuracy: 0.9583 - val_loss: 0.0253 - val_accuracy: 1.0000
Epoch 

In [14]:
# 평가, 예측
loss, acc = model.evaluate(x_test, y_test)
print('loss : ', loss)
print('accuracy : ', acc)

# result = model.evaluate(x_test, y_test)
# print(result[0])
# print(result[1])

1/1 [==============================] - 0s 1ms/step - loss: 0.0377 - accuracy: 1.0000
loss :  0.037650417536497116
accuracy :  1.0
1/1 [==============================] - 0s 2ms/step - loss: 0.0377 - accuracy: 1.0000
0.037650417536497116
1.0


In [17]:
# predict
y_predict = model.predict(x_test)
print(y_predict)

# armax 
y_predict = y_predict.argmax(axis=1)
print(y_predict) 
# print(y_test)
y_test= y_test.argmax(axis=1)
print(y_test)

[[9.99931216e-01 6.87454231e-05 3.23939211e-20]
 [5.86912793e-04 9.98944819e-01 4.68270795e-04]
 [1.58736775e-08 2.09137768e-01 7.90862262e-01]
 [2.18941292e-08 1.01516180e-01 8.98483813e-01]
 [9.67379137e-08 3.29509556e-01 6.70490324e-01]
 [7.69889215e-03 9.92298663e-01 2.43979639e-06]
 [1.30663524e-04 9.94890332e-01 4.97898413e-03]
 [1.84573971e-11 1.22652214e-03 9.98773515e-01]
 [9.99989152e-01 1.08479944e-05 1.45292467e-21]
 [9.99934435e-01 6.55069744e-05 2.96446875e-19]
 [9.99879599e-01 1.20411845e-04 7.54287079e-19]
 [9.99888539e-01 1.11438967e-04 5.61718812e-19]
 [3.13523960e-05 8.91662538e-01 1.08306035e-01]
 [9.99999404e-01 5.63053447e-07 3.91431733e-26]
 [9.99797046e-01 2.02951924e-04 4.38780892e-18]
 [4.66697893e-05 9.75000143e-01 2.49531511e-02]
 [8.61526885e-08 9.73739102e-02 9.02625978e-01]
 [9.99979854e-01 2.01367620e-05 2.81364496e-21]
 [9.99741614e-01 2.58398562e-04 3.46045901e-18]
 [9.99999166e-01 8.05417471e-07 3.87709160e-25]
 [4.97789988e-05 9.99476254e-01 4.739630

In [18]:
# 정확도 
acc = accuracy_score(y_test, y_predict)
print('정확도(accuracy) : ', acc)

정확도(accuracy) :  1.0
