In [3]:
from keras.preprocessing.text import Tokenizer

text1 = '나는 인공지능이 진짜 매우 매우 정말 재미있어서 시간이 엄청 엄청 매우 잘 간다'
text2 = '나는 매우 긍정적이고 성격이 밝으며 밥도 매우 매우 잘 먹는다'


token = Tokenizer()
token.fit_on_texts([text1, text2])  # fit하면서 index가 생성됨

print(token.word_index) # 빈도가 높은 index가 앞에 프린트되고 다음 순서대로 프린트 됨

x = token.texts_to_sequences([text1, text2])
print(x) 

from tensorflow.python.keras.utils.np_utils import to_categorical

x_new = x[0] + x[1]
print(x_new)


# x = to_categorical(x_new)
# print(x)
# print(x.shape)

{'매우': 1, '나는': 2, '엄청': 3, '잘': 4, '인공지능이': 5, '진짜': 6, '정말': 7, '재미있어서': 8, '시간이': 9, '간다': 10, '긍정적이고': 11, '성격이': 12, '밝으며': 13, '밥도': 14, '먹는다': 15}
[[2, 5, 6, 1, 1, 7, 8, 9, 3, 3, 1, 4, 10], [2, 1, 11, 12, 13, 14, 1, 1, 4, 15]]
[2, 5, 6, 1, 1, 7, 8, 9, 3, 3, 1, 4, 10, 2, 1, 11, 12, 13, 14, 1, 1, 4, 15]


In [2]:
############################### 원 핫으로 수정 #############################
from sklearn.preprocessing import OneHotEncoder
import numpy as np

onehot_encoder = OneHotEncoder(categories='auto', sparse=False)
x = np.array(x_new)
print(x.shape)  
x = x.reshape(-1, 1)
print(x.shape)  
onehot_encoder.fit(x)
x = onehot_encoder.transform(x)
print(x)
print(x.shape)  

(23,)
(23, 1)
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 