# Wine 데이터를 사용하여 다중분류하기

### One Hot Encoding의 다른 방법 찾기

In [30]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
from keras.utils import to_categorical
from sklearn import datasets
from sklearn.datasets import load_wine
from sklearn.metrics import r2_score, accuracy_score
from sklearn.model_selection import train_test_split
import time

In [31]:
# 1. 데이터
datasets = load_wine()
x = datasets.data
y = datasets.target

print(x.shape, y.shape)

(178, 13) (178,)


In [32]:
# One Hot Encoding 01
y= to_categorical(y)

print(y)
print(y.shape)  # (178, 3)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [29]:
# One Hot Encoding 02
# y =pd.get_dummies(y)

# print(y)

In [33]:
x_train, x_test, y_train, y_test = train_test_split(
  x, y, train_size=0.8, shuffle=True, random_state=72
)

print(x_train.shape, y_train.shape) # (142, 13) (142, 3)

(142, 13) (142, 3)


In [34]:
#2. 모델구성
model = Sequential()
model.add(Dense(20, activation='linear',input_dim=13))
model.add(Dense(50, activation='relu')) # elu, swish 등등
model.add(Dense(100, activation='relu'))
model.add(Dense(70, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(3,activation='softmax'))


In [35]:
#3. 컴파일, 훈련
model.compile(loss='categorical_crossentropy', optimizer='adam', 
              metrics=['accuracy'])

earlyStopping = EarlyStopping(monitor='val_loss', patience=50, mode='min', verbose=1,
                              restore_best_weights=True)

start_time = time.time()
hist = model.fit(x_train, y_train, epochs=1000, batch_size=100,
                 validation_split=0.2, 
                 callbacks=[earlyStopping], verbose=1)
end_time = time.time() - start_time

print('걸린 시간 : ', end_time)  # Epoch 00106: early stopping
                                 # 걸린 시간 :  9.58253288269043S

Epoch 1/1000
2/2 [==============================] - 0s 186ms/step - loss: 67.0130 - accuracy: 0.3894 - val_loss: 28.9777 - val_accuracy: 0.2414
Epoch 2/1000
2/2 [==============================] - 0s 36ms/step - loss: 26.5531 - accuracy: 0.2566 - val_loss: 9.0439 - val_accuracy: 0.3103
Epoch 3/1000
2/2 [==============================] - 0s 41ms/step - loss: 10.0950 - accuracy: 0.3009 - val_loss: 7.3789 - val_accuracy: 0.6552
Epoch 4/1000
2/2 [==============================] - 0s 42ms/step - loss: 9.8937 - accuracy: 0.5221 - val_loss: 13.0884 - val_accuracy: 0.4483
Epoch 5/1000
2/2 [==============================] - 0s 40ms/step - loss: 13.9445 - accuracy: 0.4602 - val_loss: 8.2738 - val_accuracy: 0.4828
Epoch 6/1000
2/2 [==============================] - 0s 48ms/step - loss: 10.2284 - accuracy: 0.3628 - val_loss: 4.7722 - val_accuracy: 0.5517
Epoch 7/1000
2/2 [==============================] - 0s 38ms/step - loss: 5.6711 - accuracy: 0.5044 - val_loss: 3.7861 - val_accuracy: 0.4483
Epoch

In [36]:
loss, acc = model.evaluate(x_test, y_test)
print('loss : ', loss)
print('acc : ', acc)

y_predict = model.predict(x_test)
y_predict = y_predict.argmax(axis=1)
y_test = y_test.argmax(axis=1)

acc = accuracy_score(y_test, y_predict)
print('정확도 : ', acc)

2/2 [==============================] - 0s 9ms/step - loss: 1.0800 - accuracy: 0.7222
loss :  1.079993724822998
acc :  0.7222222089767456
정확도 :  0.7222222222222222
